## <h1 style='font-size:40px'> Solving Linear Equations </h1>

<h2 style='font-size:30px'> 2.1
Vectors and Linear Equations</h2>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            O problema central da Álgebra Linear é a solução de sistemas de equações, sendo estas, muitas vezes, lineares. Por "linear", entenda, que as variáveis são somente multiplicadas por coeficientes.
        </li>
        <li>
            Sistemas de Equações buscam, nada mais, do que o ponto no plano em que as equações de todas as linhas intercedem.
        </li>
    </ul>
</div>

<h4 style='font-size:30px;font-style:italic;text-decoration:underline'> Exemplo</h4>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Um sistema de equações pode ser representado de diferentes maneiras. Vamos usar um exemplo simples para ilustrarmos isso.
        </li>
    </ul>
</div>

<center style='font-size:20px'> 
    $$\begin{cases}
        x-2y=1\\
        3x+2y=11
    \end{cases}
    $$
</center>

 <center style='font-size:20px;margin-top:20px'> 
        <figure>
            $$x \begin{bmatrix}1\\3\end{bmatrix}+y\begin{bmatrix}-2\\2\end{bmatrix}=\begin{bmatrix}1\\11\end{bmatrix}$$
            <figcaption style='font-size:15px'> Note que podemos representar o sistema de equações como uma combinação linear, também! </figcaption>
        </figure>
    </center>

 <center style='font-size:20px;margin-top:20px'> 
        <figure>
            $$\begin{bmatrix}1 & -2\\ 3  & 2\end{bmatrix} \begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}1\\11\end{bmatrix}$$
            <figcaption style='font-size:15px'> O sistema ainda pode ser escrito como uma multiplicação de uma matriz com um vetor.</figcaption>
        </figure>
    </center>

 <center style='margin-top:20px'> 
        <figure>
            <img src='img/01_system_plane.png'>
            <figcaption> Observe que a solução do sistema $(3,1)$ é justamente a interseção das retas.</figcaption>
        </figure>
    </center>

<h3 style='font-size:30px;font-style:italic'> Three Equations in Three Unknowns</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
            No momento, vamos tentar solucionar sistemas em que a quantidade de equações é a mesma de variáveis. Nesse tipo de problema, costuma-se haver uma única solução.
        </li>
     </ul>
</div>

<h3 style='font-size:30px;font-style:italic'>The Matrix Form of the Equations</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Aqui é ensinado como devemos efetuar a multiplicação entre uma matriz $A$ com um vetor $x$. Deveremos efetuar um dot product entre cada vetor-linha de $A$ com $x$, dando origem a um dos componentes de $b$.
        </li>
     </ul>
</div>

 <center style='font-size:20px;margin-top:20px'> 
        <figure>
            $$Ax=\begin{bmatrix}\text{row 1}\cdot{x} \\
                  \text{row 2}\cdot{x} \\
                  \text{row 3}\cdot{x}
            \end{bmatrix}=b$$
            <figcaption style='font-size:15px'> Ilustração da multiplicação entre $A$ e $x$.</figcaption>
        </figure>
    </center>

<h4 style='font-size:30px;font-style:italic;text-decoration:underline'> Matriz Identidade</h4>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            A matriz identidade é uma espécie de matriz quadrada cuja diagonal principal é constituída de 1's, enquanto que todos os demais componentes são 0's. 
        </li>
        <li>
            Quando a multiplicamos com um vetor, o resultado da operação será o próprio vetor.
        </li>
    </ul>
</div>

In [12]:
# Realizando um breve exemplo com um vetor de 4 componentes.
import numpy as np

I = np.identity(4)
x = np.linspace(1, 4, 4)

print('Identity:\n', I, '\n\nx:\n', x)

Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

x:
 [1. 2. 3. 4.]


In [13]:
# Observe que o produto da multiplicação é o próprio x.
np.matmul(I,x)

array([1., 2., 3., 4.])

<h3 style='font-size:30px;font-style:italic'> Matrix Notation</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Um componente específico de uma matriz $A$ pode ser identificado como $a_{ij}$, ou $A(i,j)$. $i$ se refere à numeração da linha, enquanto que $j$ da coluna em que o dado número se encontra.
        </li>
     </ul>
</div>

<h3 style='font-size:30px;font-style:italic'> Comprovando a Viabilidade de um Sistema de Equações</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Um sistema de equações que tenha solução possui algum vetor $y$ que, quando multiplicado por cada vetor-coluna de $A$ gera o vetor $0$. Da mesma forma, o produto escalar com $b$ deve se resultar em $0$, também.
        </li>
        <li>
            Vamos descobrir a viabilidade de uma solução para o sistema abaixo.
        </li>
     </ul>
</div>

<center style='font-size:20px;margin-top:20px'> 
                 $$
                \begin{bmatrix} 
                1 & 3 & 5 \\
                1 & 2 & -3 \\
                2 & 5 & 2
                \end{bmatrix}
                \begin{bmatrix} 
                x \\
                y \\
                z
                \end{bmatrix} 
                =
                \begin{bmatrix} 
                4 \\
                5 \\
                8
                \end{bmatrix} 
                $$
</center>

In [1]:
import numpy as np
A = np.array([[1,3,5], [1,2,-3], [2,5,2]])
b = np.array([4,5,8])

In [4]:
# Observe que, multiplicando cada vetor-coluna de A com (1,1,-1), ficamos com (0,0,0).
# Já o produto escalar desse vetor com b resulta em 1. Portanto, podemos dizer que esse
# sistema não tem solução.

y = np.array([1,1,-1])
np.matmul(A.T,y), np.dot(y,b)

(array([0, 0, 0]), 1)

<h2 style='font-size:30px'> 2.2
The Idea of Elimination</h2>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Em sistemas em que a quantidade de equações e variáveis é igual, podemos resolvê-los pelo método de eliminação.
        </li>
        <li>
                A ideia é transformarmos cada equação, de modo que o sistema passe a ter a forma de um <i> triângulo retângulo</i>. A última equação deve apresentar apenas uma variável, a de cima duas, e assim por diante.
        </li>
    </ul>
</div>

<figure>
        <center style='margin-top:20px'>
            <img src='img/02_triangle.png'>
                <figcaption> Exemplo da aplicação da Eliminação.</figcaption>
        </center>
    </figure>

<h3 style='font-size:30px;font-style:italic'> Algoritmo de Eliminação</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Devemos eliminar as variáveis da esquerda para a direita. Vamos identificar $i$ como índice de linhas. Note que a matriz de coeficientes é quadrada.
            $$\begin{bmatrix} 
                a_{11} & a_{12} & a_{13} \\ 
                a_{21} & a_{22} & a_{23} \\
                a_{31} & a_{32} & a_{33}
            \end{bmatrix} \begin{bmatrix} x\\y\\z \end{bmatrix}=\begin{bmatrix} b_1\\ b_2\\b_3 \end{bmatrix}$$
        </li>
        <li>
            Como primeiro passo, devemos eliminar a primeira variável de todas as equações, fora a primeira. Para isso, subtraímos a equação de i-ésima linha por $\frac{a_{i1}}{a_{11}}\times{\text{equation}_1}$. Observe que todas elas ficarão $0x$.
        </li>
        <li>
            Em seguida, eliminamos a segunda variável usando a equação da segunda linha. Agora, subtraímos cada equação $i$ das linhas debaixo por $\frac{a_{i2}}{a_{22}}\times{\text{equation}_2}$.
        </li>
     </ul>
</div>

<h4 style='font-size:30px;font-style:italic;text-decoration:underline'> Fórmula Geral da Eliminação</h4>
<div> 
    <ul style='font-size:20px'>
        <li> 
            A Eliminação da i-ésima variável da j-ésima equação do sistema pode ser escrita da seguinte maneira:
            <center style='font-size:20px;margin-top:20px'>
            $\text{equation}_j=\frac{a_{ji}}{a_{ii}}\times{\text{equation}_i}, \forall j=i+1\dotsc N$
            </center>
        </li>
        <li style='margin-top:20px'>
            Considere como $N$ a quantidade de equações do sistema. Chamamos $a_{ii}$ de <i> pivot</i>, enquanto $\frac{a_{ji}}{a_{ii}}$ de <i> multiplier</i>.
        </li>
     </ul>
</div>

<h3 style='font-size:30px;font-style:italic'> Breakdown of Elimination</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Os sistemas de equações podem falhar em três situações específicas. Nós as analisaremos com mais detalhe a seguir:
        </li>
     </ul>
</div>

<h4 style='font-size:30px;font-style:italic;text-decoration:underline'> Ausência de Solução</h4>
<div> 
    <ul style='font-size:20px'>
        <li> 
            O sistema tem ausência de solução quando não há um ponto de interseção entre as linhas.
        </li>
        <li>
            Descobrimos isso quando o processo de eliminação leva a um <i>pivot</i> 0 igual a um número $\neq{0}$.
        </li>
     </ul>
</div>

<figure>
        <center style='margin-top:20px'>
            <img src='img/02_no_solution.png'>
                <figcaption> Exemplo de um sistema sem solução.</figcaption>
        </center>
    </figure>

<figure>
        <center style='margin-top:20px'>
            <img src='img/02_no_solution_2.png'>
                <figcaption> Observe que as retas desse sistema nunca se cruzam, e a combinação linear dos vetores-coluna de coeficientes nunca produzirá $b$.</figcaption>
        </center>
    </figure>

<h4 style='font-size:30px;font-style:italic;text-decoration:underline'> Infinitas Soluções</h4>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Obtemos infinitas soluções, quando todas as equações do sistema são iguais. Nessa situação, a solução seriam todos os pontos atravessados pela reta.
        </li>
        <li>
            Descobrimos essa situação, quando o processo de eliminação nos leva a um <i>pivot</i> 0 igual a 0.
        </li>
     </ul>
</div>

<figure>
        <center style='margin-top:20px'>
            <img src='img/02_infinite_solutions.png'>
                <figcaption> Exemplo de um sistema com infinitas soluções.</figcaption>
        </center>
    </figure>

<figure>
        <center style='margin-top:20px'>
            <img src='img/02_infinite_solutions_2.png'>
                <figcaption> Observe como as equações do sistema, na verdade, são a mesma reta. Isso nos leva a ter infinitas combinações lineares dos vetores-coluna como solução.</figcaption>
        </center>
    </figure>

<h4 style='font-size:30px;font-style:italic;text-decoration:underline'> Linhas na Ordem Inapropriada (Breakdown Temporário)</h4>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Idealmente, desejamos eliminar as variáveis da esquerda para a direita, de modo a criarmos um triângulo retângulo de ponta cabeça.
        </li>
        <li>
            No entanto, é possível que recebamos um sistema com as variáveis da esquerda já zeradas nas equações de cima. Nessa situação, o reordenamento delas será o suficiente para a solução do problema.
        </li>
     </ul>
</div>

<figure>
        <center style='margin-top:20px'>
            <img src='img/02_ordering.png'>
                <figcaption> Reordenamento das Equações.</figcaption>
        </center>
    </figure>

In [7]:
! git add .
! git commit -am 'Explicar o conceito de row e column pictures referenciados pelo livro'
! git push

[master 8fee08b] Falar sobre os casos de falha dos sistemas de equação
 1 file changed, 44 insertions(+), 18 deletions(-)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 24 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 986 bytes | 986.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/felipesveiga/linear-algebra.git
   9c8ced0..8fee08b  master -> master


<p style='color:red'> Expliquei os casos de falha de Sistemas Lineares; Explicar o conceito de row e column pictures referenciados pelo livro; Continuar de Elimination from A to U; Acho legal programar uma classe que aplique a Eliminação Gaussiana
</p>